server:
  port: 8010

spring:
  application:
    name: dicoveryservice

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8010/eureka
  instance:
    preferIpAddress: true
