server:
#  port: 8001
  port: ${PORT:0}

spring:
  application:
    name: users-ws

  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

eureka:
  instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}  
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka

gateway:
  ip: 192.168.1.7